name: CI

on:
  push:
    branches:
      - main
      - dev_CI/CD

jobs:
  build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.12"]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: myenv
        python-version: ${{ matrix.python-version }}  # Specify the Python version
        auto-update-conda: true
        auto-activate-base: false
        miniconda-version: "latest"
    - name: install gdal (conda) and other pyproject.toml dependencies (pip)
      run: |
        conda install gdal
        pip install -e .
